### ISSUE TITLE
Disabling webworkers

### ISSUE THREAD

**Issue by leonardorame** [cornerstonejs/cornerstoneWADOImageLoader#157]
Hi, I'm trying to implement a simple viewer to be run from a CDRom but I found webworkers won't run from the filesystem.

Is there a way to use cornerstoneWADOImageLoader without webworkers?.

Leonardo.

**Comment by dannyrb** [comment]
You _should_ be able to run WebWorkers locally, so long as the paths are relative, and not in the parent directory. Are you getting a security error (or any other kind of error)?

I would hazard against a "disable webworkers" solution unless you absolutely have to go that route, or in specific [performance related situations](https://github.com/cornerstonejs/cornerstoneWADOImageLoader/issues/150). I don't believe there is currently an _existing_ configuration to achieve your desired effect (@swederik, feel free to correct me), but I'd be open to accepting a PR that extends `cornerstoneWADOImageLoader`.

**Comment by swederik** [comment]
I've just merged some commits to let you do this. You can set useWebWorkers: false and it will decode synchronously instead. See https://github.com/cornerstonejs/cornerstoneWADOImageLoader/commit/a9b408f5562bde5543fc6986bd23fbac9d676562

As @dannyrb said, it's a lot worse for your UI to avoid web workers. We added the flag because we wanted to do some server-side rendering with Cornerstone and it was a pain to get the workers running in Node.

**Comment by leonardorame** [comment]
Thanks @swederik, I'll take a look.

**Comment by kofifus** [comment]
Hi @swederik @dannyrb   , the moment I set useWebWorkers to false I get exceptions 'OpenJPEG decoder not loaded' and  'No JPEG-LS decoder loaded' .. what am I missing ?
