### ISSUE TITLE
Use wadouri/loadimage with other loader

### ISSUE THREAD

**Issue by adreyfus** [cornerstonejs/cornerstoneWADOImageLoader#165]
To avoid copying / pasting the loadImage function, I need to use it with other loader (and/or other schemes).

To do that, we can:
- provide the specific loader in a new parameter `loader`,
- provide the specific loader in `options.loader` (PR #166),
- provide the specific `getLoaderForScheme()` function in a new parameter `getLoader`
- provide the specific `getLoaderForScheme()` function in `options.getLoader`
- export functions that permit to owerwrite the function `wadouri.getLoaderForScheme()`

Is there a way that you prefer ?

**Comment by adreyfus** [comment]
@dannyrb @swederik

**Comment by dannyrb** [comment]
What other loader uses the `wadouri` loader? If two or more loader's use the same loader logic, what makes them different other than their registered scheme?

I'm sorry. I'm probably just not following the use case correctly. Any/all information you can provide to help my wrap this around my head would be appreciated 👍

**Comment by adreyfus** [comment]
Hi @dannyrb,

The main interest I have to call "wadouri.loadImage" with other (specific) loaders, is to use its dataSetCacheManager for all of them.

**Comment by dannyrb** [comment]
I "think" we resolved this issue when we merged #166? If not, is there an existing PR that this should be tied to? I'm probably mistaken, but doesn't the `sharedCacheKey` allow loaders to share the same dataSetCache?

**Comment by lyan2000** [comment]
> I "think" we resolved this issue when we merged #166? If not, is there an existing PR that this should be tied to? I'm probably mistaken, but doesn't the `sharedCacheKey` allow loaders to share the same dataSetCache?

I accidentally responded in  (#165.).
Copied here

My understanding is that the wadouri loader does the following

retrieve the data into a buffer
use dicom parser along with a bunch of third party pixel decoders to decode the buffer and create an image object
cache some meta data so that it can be used later
Step 1 is hard coded to either XHR or file. The code in step 2 is quite involved. So if the user wants to create image from DICOM stream other than XHR or file, the simplest way is to override the loader, which will avoid lots of copy/paste.

I cannot register the wadouri loadImage function with another scheme, because the loader will look up the scheme and decide on how the data can be downloaded (step 1). Without an option, the scheme will have to match one of 'dicomweb', 'wadouri', or 'dicomfile', the first two of which map to XHR request, the third maps to loadFileRequest, or it will be undefined.

I am using this option right now, but stumbled on the stack tool in cornerstoneTools, where I am not able to inject my loader.
