### ISSUE TITLE
How to get more meta data

### ISSUE THREAD

**Issue by superbull** [cornerstonejs/cornerstoneWADOImageLoader#202]
I want to read more metaData from image, e.g. `00200013`.

It seems the default `metaDataProvider` did not provider this.

How do I read more meta data without modify the source code and build the library myself?

**Comment by dannyrb** [comment]
Hmm.. Without modifying the source code? I don't know off-hand. Our `metaDataProvider` has something like this:

```
// A test type that returns all metaData for a given imageId
  if (type === 'kitchenSink') {
    return {
      kitchen: 'HelloWorld',
      sink: metaData,
    }
  }
```

Which would return everything.

You might be able to access the `metDataManager` directly to grab that data? Using it's `get` method.

```
function get(imageId) {
  return imageIds[imageId.toUpperCase()]
}
```

If you play around and think the API or extensibility could be improved, please don't hesitate to create a new issue or pull request.

**Comment by swederik** [comment]
I think you might have to use image.data by default for arbitrary tags instead of using the metadata provider.

````javascript
cornerstone.loadImage(imageId).then(function(image) {
    console.log(image.data.string('x00200013')) // or use intString, int16, etc..
});
````

You can also get the Image object from the Image Cache after it's loaded.

````javascript
const image = cornerstone.imageCache.imageCache[imageId].image
````

I do think that this is a bit of an omission though. I can see how it would be useful for the metaData provider to be able to return the dicomParser dataSet after the image has been loaded. I think the reason we haven't run into this issue is because in the OHIF Viewer we are typically populating the metaData provider using information from WADO-RS RetrieveMetadata, not the DICOM Part 10 files.

**Comment by superbull** [comment]
@dannyrb OK, I think in general there should be an optional configuration settings for the `cornerstoneWADOImageLoader`, which can specify the additional meta data user wants.

**Comment by superbull** [comment]
@swederik Thanks for you code example, this really saves my life.

**Comment by dannyrb** [comment]
I think we've answered the heart of your question here, @superbull. I'm open to expanding the API to make it easier to accomodate your use case. If you have a proposal around how you think we should approach this, please feel free to open a new issue for discussion.
