### ISSUE TITLE
webpack integration

### ISSUE THREAD

**Issue by AdrianLsk** [cornerstonejs/cornerstoneWADOImageLoader#212]
Hi, I am trying to use the library in my react component and having trouble to integrate it with webpack. 
The bottleneck is the integration of minified codec and webworker scripts.

I modified the dicom file example but the loadImage method didn't work, so I turned off the webworkers.

Then I realized that the codec OpenJPEG wasn't loading and resulted in this [error](https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/a9b408f5562bde5543fc6986bd23fbac9d676562/src/shared/decoders/decodeJPEG2000.js#L128) 

Imports in my react component:
```[javascript]
import * as cornerstone from 'cornerstone-core';
import * as cornerstoneTools from 'cornerstone-tools';
import * as cornerstoneWADOImageLoader from 'cornerstone-wado-image-loader';
cornerstoneWADOImageLoader.external.cornerstone = cornerstone;
import 'OpenJPEG';
```

[Cornerstone's OpenJPEG github](https://github.com/cornerstonejs/openjpeg) says the codec should be loaded from the js file as a global object.

I tried to bundle it with webpack, as an external:

```[javascript]
externals: {
    OpenJPEG: {
      root: [path.join(VENDOR_ROOT, 'openJPEG-FixedMemory'), 'OpenJPEG'],
     },
  },
``` 
but it didn't work. Can anyone help?

**Comment by AdrianLsk** [comment]
UPDATE:

I managed to load the codec function OpenJPEG using `script-loader` package by adding to to my react component js file `import 'script-loader!./openJPEG-FixedMemory.js';`

It takes quite some time to load the script. But then I get a different error  when using the image loader:

```javascript
VM46887:1 Uncaught (in promise) TypeError: Cannot read property 'slice' of null
    at parseJSFunc (eval at module.exports (addScript.js?3fe7:27), <anonymous>:1:9335)
    at eval (eval at module.exports (addScript.js?3fe7:27), <anonymous>:1:9497)
    at OpenJPEG (eval at module.exports (addScript.js?3fe7:27), <anonymous>:1:10615)
    at o (cornerstoneWADOImageLoader.min.js:2)
    at c (cornerstoneWADOImageLoader.min.js:2)
    at t.default (cornerstoneWADOImageLoader.min.js:2)
    at t.default (cornerstoneWADOImageLoader.min.js:2)
    at eval (cornerstoneWADOImageLoader.min.js:2)```

Has anyone managed to get this working with webpack?

**Comment by hanhanhan** [comment]
Hi, I think I'm having the same problem(s), so I'm going to put the description here instead of opening a new issue.

# Difficulties using cornerstone-wado-image-loader as a Module

I have tried to use the Wado image loader both with React, and with just a build tool, and run into difficulties.

I can't pin it down to one bug, but will show what I've tried:

# React Example

## Setup
With React, this code sandbox was used:
[https://codesandbox.io/s/716p511106]


[Setup is a react component based on a working example from @swederik referenced in the sandbox](https://codesandbox.io/s/716p511106). I swapped out the `cornerstone-web-image-loader` for `cornerstone-wado-image-loader` (and associated URI, registrations, dicomParser, config, see top of file `index.js` and `componentDidMount method line 110`).

I also added an assets folder and config referencing the uploaded `cornerstoneWADOImageLoaderCodecs.js` and `cornerstoneWADOImageLoaderWebWorker.js`

## Problems Using React with WadoImageLoader:

- When uploading `cornerstoneWADOImageLoaderCodecs.js`, the codesandbox sees an error:

  `SyntaxError /src/assets/cornerstoneWADOImageLoaderCodecs.js: Unexpected token (1:121)`

  or for the minified version:
  `/src/assets/cornerstoneWADOImageLoaderCodecs.min.js: Unexpected token (1:125)`

  I do not see the issue as the first line is a comment that is < 120 chars, but something is making it choke.

- With the config file present and the config used, there is no error, however the image doesn't display.

- A colleague [got this to work](https://codesandbox.io/s/523mjk8rwx) by using
  `cornerstoneWADOImageLoader.configure({ useWebWorkers: false });`

# No React

## Setup

[Setup is based on Cornerstone's example code, but using npm packages bundled with Parcel instead of global space.](https://codesandbox.io/s/wlvj9029w)

## Problems Using Modules with Cornerstone WadoImageLoader

- Again when uploading `cornerstoneWADOImageLoaderCodecs.js`, the codesandbox sees the same error

- Using the `useWebWorkers: false` configuration workaround throws `Unhandled Rejection (Error) - OpenJPEG decoder not loaded`, which you can see by uncommenting line 25 in [index.js](https://codesandbox.io/s/wlvj9029w)

**Comment by AdrianLsk** [comment]
@hanhanhan thanks for sharing the codesandboxes!

I managed to make the web-worker React example work by using a piece of code from [here](https://github.com/cornerstonejs/cornerstoneWADOImageLoader/blob/dc066c5b993a6c1de2e4345843fb957b0887f82e/examples/utils/customWebWorkersConfig.js)

Here is a working [Codesandbox](https://codesandbox.io/s/rm1y2l1xz4)

**Comment by hanhanhan** [comment]
@AdrianLsk thanks for figuring it out and introducing me to `Blob` and `importScripts`! Time for me to learn more about webworkers.

**Comment by JesusParra** [comment]
Thanks a lot, I was trying to get it work whit react and I had the same problem with webworkers. I use window.location to get the scripts form same server:

`function getBlobUrl(url) {
  const baseUrl = window.URL || window.webkitURL;

  let urlServer = window.location.href;

  console.log("url: ", urlServer);
  const blob = new Blob([`self.importScripts('${ urlServer + url}')`], {
    type: "application/javascript"
  });`

**Comment by nisalup** [comment]
I believe this is a problem with routing in react. React keeps routing the web worker path to the website and serves html, and hence the` unexpected token <`, as it tries to parse the served html. 
If someone very familiar with react can find a way to refer file in node modules, without having to use blobs or external files, it would be great.
I currently use @AdrianLsk 's solution but would like to move to a dependencyless solution, as medical viewers can be used in places with no internet access.
